### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by klauspost** [comment]
@harshavardhana go fmt changed between these versions.

**Comment by harshavardhana** [comment]
sio tests are failing apparently for some time now not sure it's related to `go` version change or not.

```diff
diff --git a/sio_test.go b/sio_test.go
index cfcbe46..a0b7e01 100644
--- a/sio_test.go
+++ b/sio_test.go
@@ -209,11 +209,11 @@ func TestReader(t *testing.T) {
                                }
 
                                plaintext := bytes.NewBuffer(nil)
-                               decReaderAt, err := DecryptReaderAt(bytes.NewReader(ciphertext.Bytes()), config)
+                               decReader, err := DecryptReader(bytes.NewReader(ciphertext.Bytes()), config)
                                if err != nil {
                                        t.Fatalf("Version %d: Test %d: Failed to create decrypted reader: %v", version, i, err)
                                }
-                               if _, err = io.Copy(plaintext, io.NewSectionReader(decReaderAt, 0, int64(ciphertext.Len()))); err != nil {
+                               if _, err = io.Copy(plaintext, decReader); err != nil {
                                        t.Fatalf("Version %d: Test %d: Failed to encrypted data: %v", version, i, err)
                                }
                                if !bytes.Equal(data, plaintext.Bytes()) {
```

This change fixes this for one test, however, ReaderAt still fails apparently

The failure seems to be exactly at this line

```go
        if len(p) > 0 {
                nn, err := io.ReadFull(r.src, r.buffer)
                if err == io.EOF && !r.finalized {
                        r.recycle()
                        r.stateErr = errUnexpectedEOF -------> HERE!!
                        return n, errUnexpectedEOF // reached EOF but not seen final package yet                                                                                              
                }
                if err != nil && err != io.ErrUnexpectedEOF {
                        r.recycle()
                        r.stateErr = err
                        return n,
```

**Comment by harshavardhana** [comment]
@aead need your help here, looks like some legitimate bug.

**Comment by harshavardhana** [comment]
The good thing is we only use DecryptReader() in MinIO so we didn't see this problem yet.

**Pull request closed without merging**
